config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :articles

  get 'welcome/index'
  
  root 'welcome#index'
  get "about" => "welcome#about"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true,
                    length: { minimum: 5 }
    
    belongs_to :user


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
    	@articles = Article.all
  	end
    
    def show
		@article = Article.find(params[:id])
	end 
  	
  	def new
		@article = Article.new 
	end 
	
	def edit
  		@article = Article.find(params[:id])
	end

	def create 
		@article = Article.new(article_params)
		
	   if @article.save
			redirect_to @article 
	    else 
			render 'new'
	  end 
	end 

	def update
  		@article = Article.find(params[:id])
 
      if @article.update(article_params)
         redirect_to @article
      	else
    	 render 'edit'
      end
    end

    def destroy
  		@article = Article.find(params[:id])
  		@article.destroy
 
 		redirect_to articles_path
    end
	private 
	
	def article_params 
		params.require(:article).permit(:title, :text)
	end 

	

end 
#First I decided to create a blog which you can input and save your articles in two columns, text and title while you are logged in. 
#Rails was the web development framework written in Ruby language. I generated new blog file, and some gems libraries (ready code) came with it. 
#I used Model View Controller software architecture for the benefits of clear separation between presentation logic and business logic. 
#Also, Resources: articles were created based on the Object Oriented Programming concept.I used Bootstrap for making a responsive interface.
#I used CRUD HTTP operation, GET, POST, PUT, DELETE by the RESTful API resource for showing, creating, updating or deleting the articles.

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about 
  end 


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
 <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %>

<%= link_to 'Show', articles_path %> |

 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="row"> 
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <!-- <div class="panel-heading center"> -->
<h1>Listing articles</h1>
<table>
  <tr>
    <th>Title</th>
    <div>
    <th>Text</th>
    </div>
    <!-- <th colspan="2"></th> -->
  </tr>
 <div>
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
</div>
</tr>

    </tr>
  <% end %>
</table>
<div>
<% if user_signed_in? %>
  <%= link_to 'New Pin', new_article_path %>
<% end %>
</div>
</div>
</table>
</div>
</div>
</div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= link_to 'Back', articles_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 <%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
     </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class= "container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Your Articles", articles_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Welcome", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <% if user_signed_in? %>
        <li>
          <%= link_to new_article_path do %>
            
          <% end %>
        </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else%>
        <li><%= link_to "Login", new_user_session_path, class: "btn btn-inverse btn-lg" %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     </head>
     <%= render "layouts/header" %>
  		 
     
    <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/about.html.erb
<h2>Creating the Blog Application</h2>
<p>I created a resource in the term used for a collection of similar objects, such as articles in this case. This method, can create, read, update and destroy items for a resource and these operations are referred to as CRUD operations.

Rails provides a resources method which can be used to declare a standard REST resource</p>
</div>

app/views/welcome/index.html.erb
<div class="panel-heading center">
<h1><%= link_to 'My Blog', controller: 'articles' %></h1> </div>
<p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>